apiVersion: v1
kind: ConfigMap
metadata:
   name: medilab-configmap
   labels:
     storage: app-configmap
   namespace: database-ns
data: 
   MEDILAB_BOOT_APP_DB_DRIVER: com.mysql.jdbc.Driver
   MEDILAB_BOOT_APP_DB_USERNAME: root
   MEDILAB_BOOT_APP_DB_PASSWORD: root
   MEDILAB_BOOT_APP_DB_TYP: mysql
   MEDILAB_BOOT_APP_DB_CONTAINER_NAME: medilab-boot-db-service
   MEDILAB_BOOT_APP_DB_PORT: "3306"
   MEDILAB_BOOT_APP_DB: medilab-monolith-app
   MEDILAB_BOOT_APP_DB_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
   
  